steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.diffords
      - -t
      - gcr.io/$PROJECT_ID/diffords-cocktails-scraper:$COMMIT_SHA
      - -t
      - gcr.io/$PROJECT_ID/diffords-cocktails-scraper:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args: [push, --all-tags, gcr.io/$PROJECT_ID/diffords-cocktails-scraper]

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.bot
      - -t
      - gcr.io/$PROJECT_ID/diffords-cocktails-bot:$COMMIT_SHA
      - -t
      - gcr.io/$PROJECT_ID/diffords-cocktails-bot:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args: [push, --all-tags, gcr.io/$PROJECT_ID/diffords-cocktails-bot]

images:
  - gcr.io/$PROJECT_ID/diffords-cocktails-scraper
  - gcr.io/$PROJECT_ID/diffords-cocktails-bot

timeout: 1800s
